In [0]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
url='https://raw.githubusercontent.com/FazlyRabbiBD/Data-Science-Book/master/data-diabetes.csv'
df = pd.read_csv(url)
df.head()

glucose  bloodpressure  diabetes
0       40             85         0
1       40             92         0
2       45             63         1
3       45             80         0
4       40             73         1

In [0]:
features=['glucose','bloodpressure']
x=df[features]
y=df.diabetes

In [0]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=5)

In [7]:
model=GaussianNB()
model.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [0]:
predictions = model.predict(x_test)

In [0]:
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve

In [16]:
#Model performance Report

 
print('Classification Report:\n',classification_report(y_test, predictions))
print('Confusion Matrix:\n',confusion_matrix(y_test, predictions))
print('Accuracy Score:',accuracy_score(y_test, predictions))
print("Precision:",metrics.precision_score(y_test, predictions))
print("Recall:",metrics.recall_score(y_test,predictions ))

Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.92      0.94       123
           1       0.92      0.97      0.95       126

    accuracy                           0.94       249
   macro avg       0.95      0.94      0.94       249
weighted avg       0.94      0.94      0.94       249

Confusion Matrix:
 [[113  10]
 [  4 122]]
Accuracy Score: 0.9437751004016064
Precision: 0.9242424242424242
Recall: 0.9682539682539683


In [22]:
new_observation = [[40,65]]
model.predict(new_observation)

array([1])

In [18]:
model.predict_proba(new_observation)

array([[2.88884850e-04, 9.99711115e-01]])